# Generated by Django 6.0.6 on 2026-06-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=20, unique=True)),
                ('player_name', models.CharField(max_length=100)),
                ('player_display_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=10)),
                ('headshot_url', models.URLField(blank=True, null=True)),
                ('season', models.IntegerField()),
                ('team', models.CharField(blank=True, max_length=10, null=True)),
                ('completions', models.IntegerField(default=0)),
                ('attempts', models.IntegerField(default=0)),
                ('passing_yards', models.FloatField(default=0)),
                ('passing_tds', models.IntegerField(default=0)),
                ('passing_interceptions', models.IntegerField(default=0)),
                ('sacks_suffered', models.IntegerField(default=0)),
                ('sack_yards_lost', models.FloatField(default=0)),
                ('passing_2pt_conversions', models.IntegerField(default=0)),
                ('passing_epa', models.FloatField(blank=True, null=True)),
                ('passing_cpoe', models.FloatField(blank=True, null=True)),
                ('pacr', models.FloatField(blank=True, null=True)),
                ('carries', models.IntegerField(default=0)),
                ('rushing_yards', models.FloatField(default=0)),
                ('rushing_tds', models.IntegerField(default=0)),
                ('rushing_fumbles', models.IntegerField(default=0)),
                ('fantasy_points', models.FloatField(default=0)),
                ('games_played', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('player_id', 'season')},
            },
        ),
    ]
