# Generated by Django 6.0.6 on 2026-06-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0002_alter_player_player_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RushingBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=20)),
                ('player_name', models.CharField(max_length=100)),
                ('player_display_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=10)),
                ('headshot_url', models.URLField(blank=True, null=True)),
                ('season', models.IntegerField()),
                ('team', models.CharField(blank=True, max_length=10, null=True)),
                ('carries', models.IntegerField(default=0)),
                ('rushing_yards', models.FloatField(default=0)),
                ('rushing_tds', models.IntegerField(default=0)),
                ('rushing_fumbles', models.IntegerField(default=0)),
                ('rushing_fumbles_lost', models.IntegerField(default=0)),
                ('rushing_first_downs', models.IntegerField(default=0)),
                ('rushing_epa', models.FloatField(blank=True, null=True)),
                ('receptions', models.IntegerField(default=0)),
                ('targets', models.IntegerField(default=0)),
                ('receiving_yards', models.FloatField(default=0)),
                ('receiving_tds', models.IntegerField(default=0)),
                ('receiving_fumbles', models.IntegerField(default=0)),
                ('receiving_fumbles_lost', models.IntegerField(default=0)),
                ('receiving_air_yards', models.FloatField(default=0)),
                ('receiving_yards_after_catch', models.FloatField(default=0)),
                ('receiving_first_downs', models.IntegerField(default=0)),
                ('receiving_2pt_conversions', models.IntegerField(default=0)),
                ('receiving_epa', models.FloatField(blank=True, null=True)),
                ('target_share', models.FloatField(blank=True, null=True)),
                ('air_yards_share', models.FloatField(blank=True, null=True)),
                ('racr', models.FloatField(blank=True, null=True)),
                ('wopr', models.FloatField(blank=True, null=True)),
                ('fantasy_points', models.FloatField(default=0)),
                ('games_played', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('player_id', 'season')},
            },
        ),
    ]
