# Generated by Django 6.0.6 on 2026-06-07 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0003_rushingback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RushingBack',
            new_name='RunningBacks',
        ),
    ]
