# Generated by Django 6.0.6 on 2026-06-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0006_tightend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=20)),
                ('player_name', models.CharField(max_length=100)),
                ('player_display_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=10)),
                ('headshot_url', models.URLField(blank=True, null=True)),
                ('season', models.IntegerField()),
                ('team', models.CharField(blank=True, max_length=10, null=True)),
                ('fg_made', models.IntegerField(default=0)),
                ('fg_att', models.IntegerField(default=0)),
                ('fg_missed', models.IntegerField(default=0)),
                ('fg_blocked', models.IntegerField(default=0)),
                ('fg_long', models.IntegerField(default=0)),
                ('pat_made', models.IntegerField(default=0)),
                ('pat_att', models.IntegerField(default=0)),
                ('pat_missed', models.IntegerField(default=0)),
                ('pat_blocked', models.IntegerField(default=0)),
                ('gwfg_made', models.IntegerField(default=0)),
                ('gwfg_distance', models.IntegerField(default=0)),
                ('fantasy_points', models.FloatField(default=0)),
                ('games_played', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('player_id', 'season')},
            },
        ),
    ]
